include:
  - local: .gitlab/phpstan.gitlab-ci.yml

variables:
  PHP_VERSION: '8.2'

stages:
  - build
  - lint

default:
  image: "php:$PHP_VERSION-cli"
  interruptible: true
  cache:
    key:
      files:
        - composer.lock
    paths:
      - vendor/
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq curl zip unzip
    # Install and run Composer
    - curl --show-error --silent "https://getcomposer.org/installer" | php
    - php composer.phar install --prefer-dist

ddev-initialize-docker:
  stage: lint
  image: ghcr.io/ddev/ddev-gitlab-ci:v1.23
  variables:
    # Remove "umask 0000" usage, so DDEV has permissions on the cloned repository
    # see https://docs.gitlab.com/runner/configuration/feature-flags.html#available-feature-flags
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: 1
    # Disable Docker SSL connection
    DOCKER_TLS_CERTDIR: ""
    # Fix "fatal: unable to access '<REPO>': Could not resolve host: <HOST>"
    FF_NETWORK_PER_BUILD: 0
  services:
    - name: docker:dind
  when: always
  script:
    - ddev start
    - ddev cypress-run
